name: 'NuGet Package Build and Release'
description: 'Build and release NuGet packages with dependency management'

inputs:
  projects:
    description: 'Project configurations in JSON format'
    required: true
  github_token:
    description: 'GitHub token for API access'
    required: true

outputs:
  changes:
    description: 'Array of filter names that were detected as changed'
    value: ${{ steps.filter.outputs.changes }}
  modified_packages:
    description: 'List of projects that were changed'
    value: ${{ steps.filter.outputs.modified_packages }}
  ordered_changes:
    description: 'List of projects in dependency order'
    value: ${{ steps.filter.outputs.ordered_changes }}
  has_nuspec:
    description: 'Whether any changed package uses nuspec'
    value: ${{ steps.filter.outputs.has_nuspec }}

runs:
  using: "composite"
  steps:
    - name: Run V2 Action
      uses: ./.github/actions/nuget-package-build-release/action2.yml
      with:
        projects: ${{ inputs.projects }}
        github_token: ${{ inputs.github_token }} 