name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  detect-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Detect Changed Packages
      id: filter
      uses: dorny/paths-filter@v3
      with:
        filters: |
          "A:LibraryA/LibraryA.csproj:B+C":
            - 'LibraryA/**'
          "B:LibraryB/LibraryB.csproj:C":
            - 'LibraryB/**'
          "C:LibraryC/LibraryC.csproj:":
            - 'LibraryC/**'

    - name: Print Changed Libraries
      run: |
        changes="${{ steps.filter.outputs.changes }}"
        if [ "$changes" = "[]" ]; then
          echo "No libraries were changed"
        else
          # Remove outer brackets and quotes
          filtered_changes=$(echo "$changes" | sed 's/^\[\|\]$//g' | sed 's/"//g')
          
          # Process each item
          echo "$filtered_changes" | tr ',' '\n' | while read -r item; do
            # Trim leading/trailing whitespace
            item=$(echo "$item" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
            if [ ! -z "$item" ]; then
              # Extract each part using exact positions
              key=$(echo "$item" | cut -d':' -f1)
              path=$(echo "$item" | cut -d':' -f2)
              deps=$(echo "$item" | cut -d':' -f3)
              # Only output if we have a valid key
              if [ ! -z "$key" ]; then
                echo "Library changed: $key (path: $path, dependencies: ${deps:-none})"
              fi
            fi
          done
        fi 