name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  detect-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Detect Changed Packages
      id: filter
      uses: dorny/paths-filter@v3
      with:
        filters: |
          "A:LibraryA/LibraryA.csproj:B+C":
            - 'LibraryA/**'
          "B:LibraryB/LibraryB.csproj:C":
            - 'LibraryB/**'
          "C:LibraryC/LibraryC.csproj:":
            - 'LibraryC/**'

    - name: Order Dependencies
      id: order
      run: |
        python3 - << 'EOF'
        import json
        import sys
        from collections import defaultdict

        def create_graph(items):
            graph = defaultdict(list)
            nodes = set()
            
            # Parse the items and build the graph
            for item in items:
                parts = item.strip('"').split(':')
                key = parts[0]
                deps = parts[2].split('+') if parts[2] else []
                nodes.add(key)
                for dep in deps:
                    if dep:
                        graph[key].append(dep)
                        nodes.add(dep)
            return graph, nodes

        def topological_sort(graph, nodes):
            # Track visited nodes and detect cycles
            visited = set()
            temp = set()
            order = []
            
            def visit(node):
                if node in temp:
                    sys.exit(f"Error: Circular dependency detected involving {node}")
                if node not in visited:
                    temp.add(node)
                    for dep in graph[node]:
                        visit(dep)
                    temp.remove(node)
                    visited.add(node)
                    order.append(node)
            
            # Visit each node
            for node in nodes:
                if node not in visited:
                    visit(node)
            
            return order

        # Get the changes from GitHub Actions environment
        changes = '${{ steps.filter.outputs.changes }}'
        if changes == '[]':
            print('::set-output name=ordered_changes::[]')
            sys.exit(0)

        # Remove brackets and split into items
        items = [item.strip() for item in changes.strip('[]').split(',')]
        
        # Create dependency graph
        graph, nodes = create_graph(items)
        
        # Get topological order
        ordered_keys = topological_sort(graph, nodes)
        
        # Filter and reorder the original items based on the topological order
        ordered_items = []
        key_to_item = {item.strip('"').split(':')[0]: item for item in items}
        for key in ordered_keys:
            if key in key_to_item:
                ordered_items.append(key_to_item[key])
        
        # Output the ordered array
        print(f"::set-output name=ordered_changes::[{','.join(ordered_items)}]")
        EOF

    - name: Print Changed Libraries
      run: |
        changes="${{ steps.order.outputs.ordered_changes }}"
        if [ "$changes" = "[]" ]; then
          echo "No libraries were changed"
        else
          # Remove outer brackets and quotes
          filtered_changes=$(echo "$changes" | sed 's/^\[\|\]$//g' | sed 's/"//g')
          
          # Process each item
          echo "$filtered_changes" | tr ',' '\n' | while read -r item; do
            # Trim leading/trailing whitespace
            item=$(echo "$item" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
            if [ ! -z "$item" ]; then
              # Extract each part using exact positions
              key=$(echo "$item" | cut -d':' -f1)
              path=$(echo "$item" | cut -d':' -f2)
              deps=$(echo "$item" | cut -d':' -f3)
              # Extract file extension without the dot
              ext=$(echo "$path" | grep -o '\.[^.]*$' | sed 's/\.//' || echo "no extension")
              # Only output if we have a valid key
              if [ ! -z "$key" ]; then
                echo "Library changed: $key (path: $path, dependencies: ${deps:-none})"
                echo "File extension: $ext"
                echo ""
              fi
            fi
          done
        fi  