name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  detect-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Detect Changed Packages
      id: filter
      uses: dorny/paths-filter@v3
      with:
        filters: |
          "A|LibraryA/LibraryA.csproj|B,C":
            - 'LibraryA/**'
          "B|LibraryB/LibraryB.csproj|C":
            - 'LibraryB/**'
          "C|LibraryC/LibraryC.csproj|":
            - 'LibraryC/**'

    - name: Print Changed Libraries
      run: |
        changes="${{ steps.filter.outputs.changes }}"
        if [ "$changes" = "[]" ]; then
          echo "No libraries were changed"
        else
          # Remove the square brackets and split into array
          changes="${changes#[}"
          changes="${changes%]}"
          if [ -z "$changes" ]; then
            echo "No libraries were changed"
          else
            changed_libs=($changes)
            for lib in "${changed_libs[@]}"; do
              echo "Library changed: $lib"
            done
          fi
        fi 