name: Build and Package Example V2

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches: [ main ]


permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  detect-changes:
    if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'Release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Run action2
        uses: ./.github/actions/nuget-package-build-release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          projects: |
            {
              "LibraryA": {
                "path": "LibraryA/LibraryA.csproj",
                "patterns": ["LibraryA/**"],
                "dependencies": []
              }
            }