name: Build and Package Example V2

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches: [ main ]


permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  detect-changes:
    if: ${{ startsWith(github.head_ref, 'Release') }}
    runs-on: ubuntu-latest
    steps:
      - name: Simple Log
        run: |
          echo "This is a test log"
          echo "Branch: ${{ github.head_ref }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Event type: ${{ github.event.action }}"
          echo "Base ref: ${{ github.base_ref }}"
          echo "Condition check: ${{ startsWith(github.head_ref, 'Release') }}"